"""
Export notes to a DOCX file using python-docx.
Returns the path of the generated file.
"""
import os
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH


def export_notes_to_docx(title: str, summary: str, keywords: list, output_dir: str) -> str:
    """
    Generate a professional DOCX of the lecture notes.

    Args:
        title:      Lecture title
        summary:    Full summary text
        keywords:   List of keyword strings
        output_dir: Directory to save the file

    Returns:
        Absolute path to the generated DOCX file.
    """
    os.makedirs(output_dir, exist_ok=True)
    safe_title = "".join(c if c.isalnum() or c in " _-" else "_" for c in title)[:60]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = os.path.join(output_dir, f"{safe_title}_{timestamp}.docx")

    doc = Document()

    # --- Document margins ---
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1.1)
        section.right_margin = Inches(1.1)

    # --- Title ---
    title_para = doc.add_heading(title, level=1)
    title_para.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = title_para.runs[0]
    run.font.color.rgb = RGBColor(0x50, 0x28, 0xB0)
    run.font.size = Pt(20)

    # Date subtitle
    date_para = doc.add_paragraph(f"Generated on {datetime.now().strftime('%A, %B %d, %Y at %H:%M')}")
    date_para.runs[0].font.color.rgb = RGBColor(0x80, 0x80, 0xA0)
    date_para.runs[0].font.size = Pt(9)
    date_para.runs[0].italic = True

    doc.add_paragraph()  # spacer

    # --- Summary Heading ---
    doc.add_heading("Executive Summary", level=2)

    for line in summary.split("\n"):
        line = line.strip()
        if not line:
            continue
        if line.startswith("•") or line.startswith("-"):
            p = doc.add_paragraph(line.lstrip("•-").strip(), style="List Bullet")
            p.runs[0].font.size = Pt(11)
        else:
            p = doc.add_paragraph(line)
            p.runs[0].font.size = Pt(11)

    doc.add_paragraph()  # spacer

    # --- Keywords ---
    if keywords:
        doc.add_heading("Key Concepts", level=2)
        kw_para = doc.add_paragraph()
        for i, kw in enumerate(keywords):
            if not kw.strip():
                continue
            run = kw_para.add_run(kw.strip())
            run.bold = True
            run.font.color.rgb = RGBColor(0x50, 0x28, 0xB0)
            run.font.size = Pt(11)
            if i < len(keywords) - 1:
                sep = kw_para.add_run("  ·  ")
                sep.font.color.rgb = RGBColor(0xA0, 0xA0, 0xB0)

    # --- Footer note ---
    doc.add_paragraph()
    footer = doc.add_paragraph("Generated by LectureMind AI  |  AI-Powered Study Assistant")
    footer.runs[0].font.color.rgb = RGBColor(0xB0, 0xB0, 0xC0)
    footer.runs[0].font.size = Pt(8)
    footer.runs[0].italic = True
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.save(out_path)
    return out_path